language: csharp
solution: Assembly-CSharp.sln
branches:
  except:
    - master
deploy:
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/onikakushi/ 2>/dev/null
    on:
      branch: oni-mod
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/watanagashi/ 2>/dev/null
    on:
      branch: wata-mod
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/tatarigoroshi/ 2>/dev/null
    on:
      branch: tata-mod
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/himatsubushi/ 2>/dev/null
    on:
      branch: hima-mod
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/meakashi/ 2>/dev/null
    on:
      branch: mea-mod
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/tsumihoroboshi/ 2>/dev/null
    on:
      branch: tsumi-mod
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/minagoroshi/ 2>/dev/null
    on:
      branch: mina-mod-test
  - skip_cleanup: true
    provider: script
    script: echo ${SSH_KEY} | base64 --decode > key && chmod 600 key && scp -o StrictHostKeyChecking=no -i key bin/Release/Assembly-CSharp.dll ${UPLOAD_SERVER}/consolearcs/ 2>/dev/null
    on:
      branch: console-arcs