namespace UMP.Wrappers
{
	internal enum EventTypes
	{
		MediaMetaChanged = 0,
		MediaSubItemAdded = 1,
		MediaDurationChanged = 2,
		MediaParsedChanged = 3,
		MediaFreed = 4,
		MediaStateChanged = 5,
		MediaSubItemTreeAdded = 6,
		MediaPlayerMediaChanged = 0x100,
		MediaPlayerNothingSpecial = 257,
		MediaPlayerOpening = 258,
		MediaPlayerBuffering = 259,
		MediaPlayerPlaying = 260,
		MediaPlayerPaused = 261,
		MediaPlayerStopped = 262,
		MediaPlayerForward = 263,
		MediaPlayerBackward = 264,
		MediaPlayerEndReached = 265,
		MediaPlayerEncounteredError = 266,
		MediaPlayerTimeChanged = 267,
		MediaPlayerPositionChanged = 268,
		MediaPlayerSeekableChanged = 269,
		MediaPlayerPausableChanged = 270,
		MediaPlayerTitleChanged = 271,
		MediaPlayerSnapshotTaken = 272,
		MediaPlayerLengthChanged = 273,
		MediaPlayerVout = 274,
		MediaPlayerScrambledChanged = 275,
		MediaListItemAdded = 0x200,
		MediaListWillAddItem = 513,
		MediaListItemDeleted = 514,
		MediaListWillDeleteItem = 515,
		MediaListViewItemAdded = 768,
		MediaListViewWillAddItem = 769,
		MediaListViewItemDeleted = 770,
		MediaListViewWillDeleteItem = 771,
		MediaListPlayerPlayed = 0x400,
		MediaListPlayerNextItemSet = 1025,
		MediaListPlayerStopped = 1026,
		MediaDiscovererStarted = 1280,
		MediaDiscovererEnded = 1281,
		VlmMediaAdded = 1536,
		VlmMediaRemoved = 1537,
		VlmMediaChanged = 1538,
		VlmMediaInstanceStarted = 1539,
		VlmMediaInstanceStopped = 1540,
		VlmMediaInstanceStatusInit = 1541,
		VlmMediaInstanceStatusOpening = 1542,
		VlmMediaInstanceStatusPlaying = 1543,
		VlmMediaInstanceStatusPause = 1544,
		VlmMediaInstanceStatusEnd = 1545,
		VlmMediaInstanceStatusError = 1546
	}
}
